<?php
/**
 * Created by PhpStorm.
 * User: rinat
 * Date: 25.09.18
 * Time: 17:24
 */

namespace App\Command;


use App\Component\AsteriskImport;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportAsteriskCommand extends Command
{
    protected  $asteriskImport;

    public function __construct($name = null, AsteriskImport $asteriskImport)
    {

        $this->asteriskImport = $asteriskImport;
        parent::__construct($name);
    }

    protected function configure()
    {
        //parent::configure(); // TODO: Change the autogenerated stub
        $this
            ->setName('app:import-asterisk')
            ->setDescription('Import data records from Asterisk')
            ->setHelp('This command is do request to asterisk');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->asteriskImport->getImport();
        sleep(1);
        $this->asteriskImport->getImport();
        //parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}