<?php
/**
 * Created by PhpStorm.
 * User: rinat
 * Date: 02.10.18
 * Time: 22:08
 */

namespace App\Command;


use App\Component\AsteriskImport;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportAsteriskPropCommand extends Command
{
    protected $asteriskImport;

    public function __construct($name = null, AsteriskImport $asteriskImport)
    {
        $this->asteriskImport = $asteriskImport;
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('app:import-asterisk-prop')
            ->setDescription('import asterisk properties')
            ->setHelp('');
        //parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {

        for($i=0;$i<10;$i++) {
            $this->asteriskImport->getImportProp();
            sleep(1);
        }

        //parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}