<?php
/**
 * Created by PhpStorm.
 * User: rinat
 * Date: 18.09.18
 * Time: 16:29
 */

namespace App\Form;

use App\Entity\Common\Role;
use App\Entity\Common\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('username')
            ->add('status')
            ->add('first_name', TextType::class)
            ->add('last_name', TextType::class)
            ->add('email', EmailType::class)
            ->add('role', EntityType::class, [
                'multiple' => true,
                'class' => \App\Entity\Common\Role::class,
                'expanded' => true,
                'required' => true
            ])
//            ->add('role', EntityType::class,[
//                'class' => Role::class
//            ])
            ->add('plain_password', PasswordType::class)
            ->add('save', SubmitType::class, ['label' => 'Сохранить']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'data_class' => \App\Entity\Common\User::class
        ]);
    }
}